spring:
  profiles:
    active: local
  server:
    port: 9090

  datasource:
    url: jdbc:mysql://localhost:3306/testjin?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qwe1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.`MySQL5InnoDBDialect
        format_sql`: true
        show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    com.tutorial: debug

jwt:
  secret: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY3MDU2MjI2MCwiaWF0IjoxNjcwNTYyMjYwfQ.rJpvMQjrdYtwOH7mfWk9sX2gGWZ-lYotBIegytUbvxY