spring:
  server:
    port: 8081
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:
  datasource:
    url: jdbc:mysql://localhost:3306/testjin?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qwe1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  #      settings:
  #        web-allow-others: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    com.tutorial: debug
